//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLOB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLOB_PostObservationQuestions
    {
        public int POQID { get; set; }
        public string Active { get; set; }
        public string POQType { get; set; }
        public string SubSection { get; set; }
        public string QuestionText { get; set; }
        public string QuestionType { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
        public Nullable<int> EditedBy { get; set; }
    }
}
