//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLOB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CLOBEntities : DbContext
    {
        public CLOBEntities()
            : base("name=CLOBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLOB_ErrorLog> CLOB_ErrorLog { get; set; }
        public DbSet<CLOB_ObservationBackground> CLOB_ObservationBackground { get; set; }
        public DbSet<CLOB_ObservationInformation> CLOB_ObservationInformation { get; set; }
        public DbSet<CLOB_ObservationsAnswers> CLOB_ObservationsAnswers { get; set; }
        public DbSet<CLOB_Observers> CLOB_Observers { get; set; }
        public DbSet<CLOB_PostObservationQuestions> CLOB_PostObservationQuestions { get; set; }
    
        public virtual ObjectResult<GetObservationInfoCounts_Result> GetObservationInfoCounts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetObservationInfoCounts_Result>("GetObservationInfoCounts");
        }
    }
}
